### ISSUE TITLE
School List & Account Setting

### ISSUE THREAD

**Issue by permlap-phola** [tatuga-camp/client-main-tatugaschool#15]
School list Endpoint

- get schools : GET /v1/schools
- create school: POST /v1/schools
- update school PATCH /v1/schools
- delete school DELETE /v1/schools

Account Setting

- get user information : GET v1/users/me
- update: PATCH v1/users
- upload photo: v1/google-storage/get-signURL/teacher
_to google stroage using SignURL (allow user to upload file from client to google cloud stroage directly ):_ 

workflow user update profile
get user photo ->
using getSignedURLTeacherService() ->
using UploadSignURLService() -> 
after complete get original url fron getSignedURLTeacherService() and pass it to - update: PATCH v1/users

**Comment by permlap-phola** [comment]
@ChunWarayut  เดี๋ยวผม install react-query เป็น data-fetching library ใน project นี้นะครับ เดี๋ยวจัดการด้าน setup ให้

**Comment by permlap-phola** [comment]
@ChunWarayut  @warodompom  เรียบร้อยครับ pull origin main มาได้ เลย

**Comment by permlap-phola** [comment]
@ChunWarayut  @warodompom  สามารถ ยิง pull request มาได้ภายในวันศุกร์ได้ไหมครับ

เดี๋ยวผมจะสร้าง issue ใหม่ให้

**Comment by ChunWarayut** [comment]
ติดเรื่อง photo อะ ว่างมั้ย

เมื่อ พ. 16 ต.ค. 2024 เวลา 22:46 Permlap Phola ***@***.***>
เขียนว่า:

**Comment by permlap-phola** [comment]
@ChunWarayut  วันนี้พอ push มาได้ไหมครับ

**Comment by ChunWarayut** [comment]
ได้ครับ

เมื่อ ศ. 18 ต.ค. 2024 เวลา 11:07 Permlap Phola ***@***.***>
เขียนว่า:

**Comment by permlap-phola** [comment]
#19
