### ISSUE TITLE
School Main dashboard

### ISSUE THREAD

**Issue by permlap-phola** [tatuga-camp/client-main-tatugaschool#20]
route /school/:id

- [x] layoutSchoolDashboard
      - [ ] sidebar
      - [ ] header
- [x] member 
react-query: getMemberBySchool()
- [x] basic information
react-query:  getSchools()
- [ ] billing and plan (hard code only ui )
- [x] invitiation 
import component \components\school\InviteJoinSchool.tsx

package
UI: primereact
UI aleart: sweetalert2
state management & service management : react-query

new package  require to install: **lodash**

Figma: https://www.figma.com/design/bdMzoyDRRIV2E4gvUIdUsK/tatuga-school?node-id=199-14750&t=VrtS7UnVoZ8aD5Y4-1

**Comment by ChunWarayut** [comment]
@permlap-phola MR 2 เรื่องก่อนครับ layoutSchoolDashboard, member https://github.com/tatuga-camp/client-main-tatugaschool/pull/31

**Comment by permlap-phola** [comment]
ได้ครับ เดียวผมลองดูให้
