### ISSUE TITLE
Responsive On Subject Part 1

### ISSUE THREAD

**Issue by permlap-phola** [tatuga-camp/client-main-tatugaschool#56]
custom tailwind to handle responsive on mobile and tablet device

- [x] subject
- [x] subject setting
- [x] AttendanceChecker.tsx
- [x] QRCode.tsx
- [x] PopUpStudent.tsx
- [x] ScorePanel.tsx
- [x] SilderPicker.tsx
- [x] StopWatch.tsx

**Comment by permlap-phola** [comment]
@ChunWarayut  ขอ pull request วันนี้ได้ไหมครับ

**Comment by permlap-phola** [comment]
@ChunWarayut  ตามงานครับ

**Comment by ChunWarayut** [comment]
พรุ่งนี้นะครับ

เมื่อ อา. 1 ธ.ค. 2024 เวลา 16:26 Permlap Phola ***@***.***>
เขียนว่า:

**Comment by permlap-phola** [comment]
@ChunWarayut  ยิง pull request มารึยังครับ ผมไม่เห็น

**Comment by ChunWarayut** [comment]
@permlap-phola  ส่ง MR ไปแล้วครับ
