### ISSUE TITLE
Create Services 2

### ISSUE THREAD

**Issue by permlap-phola** [tatuga-camp/client-main-tatugaschool#6]
- [x] board-task
- [x] class
- [x] comment-assignment
- [x] file-assignment
- [x] file-on-student-assignment
- [x] google stroage
- [x] member-on-school
- [x] school
- [x] score-on-student
- [x] score-on-subject

**Comment by permlap-phola** [comment]
@ChunWarayut  อย่าลืม pull origin main ก่อนเริ่ม pull request นะครับ ผมแก้ไข API #22a74b8

**Comment by permlap-phola** [comment]
@ChunWarayut  ผมทำ postman เสร็จหมดแล้วนะครับ รบกวนของานในวันอังคารหน้าด้วยครับ

**Comment by permlap-phola** [comment]
@ChunWarayut  ขอภายในวันนี้ได้ไหมครับ ขอบคุณครับ

**Comment by ChunWarayut** [comment]
พี่เอ็มส่งไปแล้วนี่ครับ

เมื่อ พ. 11 ก.ย. 2024 เวลา 20:28 Permlap Phola ***@***.***>
เขียนว่า:

**Comment by permlap-phola** [comment]
เห็นแล้วครับ 🙏
