### ISSUE TITLE
Create Service 3

### ISSUE THREAD

**Issue by permlap-phola** [tatuga-camp/client-main-tatugaschool#8]
- [x] skill
- [x] skill-on-assignment
- [x] student
- [x] student-on-assignment
- [x] student-on-subject
- [x] subject
- [x] teacher-on-subject
- [x] team

@ChunWarayut  save response example ทั้งหมดจาก endpoint ด้านบนแล้วนะครับ อันไหนไม่มีแจ้งมาได้เลยครับ

**Comment by permlap-phola** [comment]
@ChunWarayut  @warodompom  พอส่ง pull request มาในวันหยุดนี้ได้ไหมครับ

**Comment by ChunWarayut** [comment]
ได้ครับ

เมื่อ พฤ. 19 ก.ย. 2024 เวลา 21:52 Permlap Phola ***@***.***>
เขียนว่า:

**Comment by permlap-phola** [comment]
#10
