### ISSUE TITLE
create auth page

### ISSUE THREAD

**Issue by permlap-phola** [tatuga-camp/client-main-tatugaschool#9]
- [x] sign in ( page route : localhost/auth/sign-in )
     - [x] create ui
     - [x] implement function
- [x] create account ( page route : localhost/auth/sign-up)
     - [x] create ui
     - [x] implement function
- [x] implement refetch token https://akhilaariyachandra.com/blog/refreshing-an-authentication-in-token-in-tanstack-query

Figma : https://www.figma.com/design/NgkQ24JwIWkjv0tEc2VSTR/Auth-Tatuga-School?node-id=0-1&m=dev&t=XeGsSM87wlnC4x0s-1

development server:https://development-server.tatugaschool.com

**Comment by permlap-phola** [comment]
@ChunWarayut  @warodompom  วันอังคารที่ 24 เดี๋ยวเรามาคุยกันเรื่อง issue นี้นะครับ

**Comment by ChunWarayut** [comment]
ครับผม

เมื่อ ส. 21 ก.ย. 2024 เวลา 18:49 Permlap Phola ***@***.***>
เขียนว่า:

**Comment by permlap-phola** [comment]
@ChunWarayut @warodompom  พอมีความคืบหน้าให้ผมช่วยๆ ดูไหมครับ

**Comment by permlap-phola** [comment]
close #11
